version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/trackjobapplications-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/trackjobapplications-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/trackjobapplications-extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/trackjobapplications-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/trackjobapplications-frontend"
    schedule:
      interval: "weekly"
