services:
  - type: web
    name: trackjobapplications-backend
    runtime: docker
    rootDir: trackjobapplications-backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    region: frankfurt
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_SSLMODE
        value: "require"
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_BACKEND
        value: "anymail.backends.resend.EmailBackend"
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: CRON_SECRET
        sync: false
