# Generated by Django 5.2.11 on 2026-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_status_955cad_idx',
            old_name='applications_status_updated_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
