MAX_IMPORT_ROWS = 1000
MAX_IMPORT_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
MAX_PAGE_SIZE_ALL = 500

MAX_TEMPLATES_PER_USER = 50
MAX_TAGS_PER_USER = 200
MAX_NOTES_PER_APPLICATION = 50
MAX_CONTACTS_PER_APPLICATION = 20
MAX_INTERVIEWS_PER_APPLICATION = 20
MAX_ATTACHMENTS_PER_APPLICATION = 10
MAX_EMAILS_PER_APPLICATION = 100

ALLOWED_IMPORT_FIELDS = {"company", "position", "status", "applied_date", "url", "source", "notes"}
FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r", "|")
MAX_PDF_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB
